import type { ColorSwatch } from "@shared/schema";

const palettes: Record<string, ColorSwatch[]> = {
  "office-assured-bright": [
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#7A8B99", keyword: "Cool Gray" },
  ],
  "office-assured-cozy": [
    { hex: "#8B3A2A", keyword: "Terracotta" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#F0E6D8", keyword: "Ivory" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "office-confidence-bright": [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#E8DDD0", keyword: "Warm Cream" },
    { hex: "#4A7C90", keyword: "Teal" },
    { hex: "#C0C0C0", keyword: "Silver" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "office-confidence-cozy": [
    { hex: "#3B2F2F", keyword: "Espresso" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#E8DDD0", keyword: "Warm Cream" },
    { hex: "#5A4A3A", keyword: "Dark Bronze" },
  ],
  "office-empathy-bright": [
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "office-empathy-cozy": [
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#A67B5B", keyword: "Warm Taupe" },
  ],
  "office-motivation-bright": [
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#4A7C59", keyword: "Fresh Green" },
    { hex: "#3B5998", keyword: "Royal Blue" },
  ],
  "office-motivation-cozy": [
    { hex: "#C73B6B", keyword: "Berry Pink" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#8B3A2A", keyword: "Terracotta" },
    { hex: "#E8DDD0", keyword: "Warm Cream" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "urban-assured-bright": [
    { hex: "#B0C4D8", keyword: "City Sky" },
    { hex: "#D5C8B8", keyword: "Champagne" },
    { hex: "#C0C0C0", keyword: "Silver Mesh" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "urban-assured-cozy": [
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#6B7B8D", keyword: "Slate" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
    { hex: "#8B4E3B", keyword: "Warm Bronze" },
    { hex: "#3D3D3D", keyword: "Charcoal" },
  ],
  "urban-confidence-bright": [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#4A90C4", keyword: "Clear Sky" },
    { hex: "#5A7D4A", keyword: "Forest Green" },
    { hex: "#C4B5A0", keyword: "Concrete Tan" },
    { hex: "#8C7A68", keyword: "Warm Earth" },
  ],
  "urban-confidence-cozy": [
    { hex: "#2D2D2D", keyword: "Charcoal" },
    { hex: "#8A6B4E", keyword: "Bronze" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
    { hex: "#4A4A4A", keyword: "Dark Gray" },
  ],
  "urban-empathy-bright": [
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#B0C4D8", keyword: "City Sky" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "urban-empathy-cozy": [
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
    { hex: "#6B5B4E", keyword: "Mocha" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
  ],
  "urban-motivation-bright": [
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#4A90C4", keyword: "Clear Sky" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#C4B5A0", keyword: "Concrete Tan" },
    { hex: "#2B3A52", keyword: "Deep Navy" },
  ],
  "urban-motivation-cozy": [
    { hex: "#C73B6B", keyword: "Berry Pink" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#3D3D3D", keyword: "Charcoal" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
  ],
  "nature-assured-bright": [
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#A8C4E0", keyword: "Open Sky" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#8FB573", keyword: "Moss" },
    { hex: "#D4B896", keyword: "Warm Sand" },
  ],
  "nature-assured-cozy": [
    { hex: "#5C7A3A", keyword: "Deep Moss" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#3D5A2E", keyword: "Forest" },
  ],
  "nature-confidence-bright": [
    { hex: "#2E5A3A", keyword: "Evergreen" },
    { hex: "#A8C4E0", keyword: "Open Sky" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "nature-confidence-cozy": [
    { hex: "#3D5A2E", keyword: "Forest" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "nature-empathy-bright": [
    { hex: "#8FB573", keyword: "Moss" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#A8C4E0", keyword: "Open Sky" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "nature-empathy-cozy": [
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#8B6F4E", keyword: "Caramel" },
  ],
  "nature-motivation-bright": [
    { hex: "#4A7C59", keyword: "Fresh Green" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#4A90C4", keyword: "Clear Sky" },
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "nature-motivation-cozy": [
    { hex: "#5C7A3A", keyword: "Deep Moss" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#3D5A2E", keyword: "Forest" },
  ],
  "restaurant-assured-bright": [
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#A67B5B", keyword: "Warm Taupe" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "restaurant-assured-cozy": [
    { hex: "#8B3A2A", keyword: "Terracotta" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
  ],
  "restaurant-confidence-bright": [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#C0C0C0", keyword: "Silver" },
    { hex: "#A67B5B", keyword: "Warm Taupe" },
    { hex: "#D4B896", keyword: "Warm Sand" },
  ],
  "restaurant-confidence-cozy": [
    { hex: "#3B2F2F", keyword: "Espresso" },
    { hex: "#8B3A2A", keyword: "Terracotta" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#2D2D2D", keyword: "Charcoal" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
  ],
  "restaurant-empathy-bright": [
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#A67B5B", keyword: "Warm Taupe" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "restaurant-empathy-cozy": [
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "restaurant-motivation-bright": [
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#4A7C59", keyword: "Fresh Green" },
    { hex: "#A67B5B", keyword: "Warm Taupe" },
  ],
  "restaurant-motivation-cozy": [
    { hex: "#C73B6B", keyword: "Berry Pink" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
  ],
  "workvan-assured-bright": [
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#6B7B8D", keyword: "Slate" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "workvan-assured-cozy": [
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
    { hex: "#3D3D3D", keyword: "Charcoal" },
  ],
  "workvan-confidence-bright": [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#C0C0C0", keyword: "Silver" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "workvan-confidence-cozy": [
    { hex: "#2D2D2D", keyword: "Charcoal" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
    { hex: "#D8CFC0", keyword: "Warm Taupe" },
  ],
  "workvan-empathy-bright": [
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "workvan-empathy-cozy": [
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "workvan-motivation-bright": [
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#8A9BAA", keyword: "Steel Blue" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "workvan-motivation-cozy": [
    { hex: "#C73B6B", keyword: "Berry Pink" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
    { hex: "#3D3D3D", keyword: "Charcoal" },
  ],
  "suburban-assured-bright": [
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#8FB573", keyword: "Moss" },
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "suburban-assured-cozy": [
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "suburban-confidence-bright": [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#8FB573", keyword: "Moss" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#C0C0C0", keyword: "Silver" },
  ],
  "suburban-confidence-cozy": [
    { hex: "#3B2F2F", keyword: "Espresso" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#D4B896", keyword: "Warm Sand" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  "suburban-empathy-bright": [
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#8FB573", keyword: "Moss" },
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#E8D5C4", keyword: "Soft Peach" },
  ],
  "suburban-empathy-cozy": [
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#D4A5A0", keyword: "Blush Rose" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#8B6F4E", keyword: "Caramel" },
  ],
  "suburban-motivation-bright": [
    { hex: "#4A7C59", keyword: "Fresh Green" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#E84B2A", keyword: "Coral Red" },
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  "suburban-motivation-cozy": [
    { hex: "#5C7A3A", keyword: "Deep Moss" },
    { hex: "#C4742A", keyword: "Burnt Orange" },
    { hex: "#D4A24E", keyword: "Marigold" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
  ],
};

const emotionalFallback: Record<string, ColorSwatch[]> = {
  bright: [
    { hex: "#F5F0E8", keyword: "Warm White" },
    { hex: "#A8C4E0", keyword: "Powder Blue" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#6B8F5E", keyword: "Sage Green" },
    { hex: "#D4B896", keyword: "Warm Sand" },
  ],
  cozy: [
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#8B6F4E", keyword: "Caramel" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#E8DFD5", keyword: "Soft Linen" },
    { hex: "#5C4033", keyword: "Dark Walnut" },
  ],
  powerful: [
    { hex: "#2B3A52", keyword: "Deep Navy" },
    { hex: "#2D2D2D", keyword: "Charcoal" },
    { hex: "#C0C0C0", keyword: "Silver" },
    { hex: "#8C7A68", keyword: "Warm Earth" },
    { hex: "#F5F0E8", keyword: "Warm White" },
  ],
  cinematic: [
    { hex: "#1A1A2E", keyword: "Midnight" },
    { hex: "#C4935A", keyword: "Amber" },
    { hex: "#4A4A4A", keyword: "Dark Gray" },
    { hex: "#D4A574", keyword: "Honey Gold" },
    { hex: "#2B3A52", keyword: "Deep Navy" },
  ],
};

const genericFallback: ColorSwatch[] = [
  { hex: "#E8DFD5", keyword: "Soft Linen" },
  { hex: "#D4B896", keyword: "Warm Sand" },
  { hex: "#8A9BAA", keyword: "Steel Blue" },
  { hex: "#6B8F5E", keyword: "Sage Green" },
  { hex: "#A67B5B", keyword: "Warm Taupe" },
];

export function getRecommendedPalette(
  environment: string | null,
  brandMessage: string | null,
  emotionalImpact: string | null
): ColorSwatch[] {
  if (environment && brandMessage && emotionalImpact) {
    const key = `${environment}-${brandMessage}-${emotionalImpact}`;
    if (palettes[key]) return palettes[key];
  }

  if (emotionalImpact && emotionalFallback[emotionalImpact]) {
    return emotionalFallback[emotionalImpact];
  }

  return genericFallback;
}
